### Title :- Data Manipulation (Numpy library) Operations Broadcasting Indexing and slicing.

Install NumPy library

In [3]:
pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: C:\Users\nihal\AppData\Local\Programs\Python\Python311\myenv\env\Scripts\python.exe -m pip install --upgrade pip


Creating NumPy Arrays

In [1]:
import numpy as np
# Create a NumPy array from a list
arr = np.array([1, 2, 3, 4, 5]) 
print("Array list \n", arr)
# Create an array of zeros with shape (3, 4) 
zeros_array = np.zeros((3, 4)) 
print("Array list zeros \n", zeros_array)
# Create an array of ones with shape (2, 3)
ones_array = np.ones((2, 3)) 
print("Array list ones \n",ones_array)
# Create a random array with shape (2, 2) 
random_array = np.random.rand(2, 2) 
print("Random Array list \n", random_array)

Array list 
 [1 2 3 4 5]
Array list zeros 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array list ones 
 [[1. 1. 1.]
 [1. 1. 1.]]
Random Array list 
 [[0.90429254 0.25580482]
 [0.95841536 0.38848013]]


Broadcasting

In [2]:
#Broadcasting example
a = np.array([1, 2, 3])
scalar = 2
result = a * scalar # Broadcasting the scalar to the array [2, 4, 6] 
print("Broadcasting", result)

Broadcasting [2 4 6]


 Array Operations

In [3]:
#Element-wise arithmetic operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 
print("addition", a + b)
print("subtraction", a- b)
print("multiplication", a* b)
print("division", a / b)

#Matrix operations
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot (matrix_a, matrix_b)  #Matrix multiplication
print("Matrix Product \n",matrix_product) 

# Statistical functions
data= np.array([10, 15, 20, 25, 30])
print(data)
mean= np.mean(data)
print("Mean", mean)
median= np.median(data) 
print("Median", median)
std_deviation = np.std(data)
print("std Deviation", std_deviation)

addition [5 7 9]
subtraction [-3 -3 -3]
multiplication [ 4 10 18]
division [0.25 0.4  0.5 ]
Matrix Product 
 [[19 22]
 [43 50]]
[10 15 20 25 30]
Mean 20.0
Median 20.0
std Deviation 7.0710678118654755


 Indexing and Slicing

In [4]:
arr = np.array([10, 20, 30, 40, 50])
#Accessing elements using indexing 
element = arr[0] # Access the first element (10) 
print("[0] ",element) 
element_2 = arr[-1] # Access the last element (50)
print("[-1] ",element_2)

[0]  10
[-1]  50


In [5]:
arr = np.array([10, 20, 30, 40, 50])
#Slicing
slice_1 = arr[1:4] # Get elements from index 1 to index 3 (20, 30, 40)
print("arr[1:4] ",slice_1)
slice_2 = arr[:3] # Get elements from the beginning up to index 2 (10, 20, 30) 
print("arr[:3] ",slice_2)
slice_3 = arr[2:] # Get elements from index 2 to the end (30, 40, 50)
print("arr[2:] ",slice_3)

arr[1:4]  [20 30 40]
arr[:3]  [10 20 30]
arr[2:]  [30 40 50]
